runtime: nodejs10

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  - url: /favicon\.png
    static_files: favicon.png
    upload: favicon\.png

  - url: /static
    static_dir: static

  - url: /images/.*\.svg
    static_dir: static/images
    http_headers:
      Access-Control-Allow-Origin: "*"

  - url: /images
    static_dir: static/images
